version: '3.7'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    volumes:
      - ./data/db:/data/db
    ports:
      - "27017:27017"

  nuxt-app:
    build: ./nuxt-app
    container_name: nuxt-app
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/bitcoin_prices

  data-collector:
    build: ./data-collector
    container_name: data-collector
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=mongodb://mongodb:27017/bitcoin_prices
